"""Write a lesson to disk: audio, study sheet, HTML with real furigana, subtitles."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from html import escape
from pathlib import Path
from typing import List, Optional, Sequence

from .levels import get_level
from .models import Lesson
from .tts.audio import UnsupportedFormat, write_clip
from .version import APP_NAME, __version__


@dataclass
class ExportResult:
    files: List[Path] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return bool(self.files)


# --------------------------------------------------------------------------
# Audio
# --------------------------------------------------------------------------


def export_audio(clip, directory: Path, stem: str, bitrate: int = 128,
                 fmt: str = "mp3") -> Path:
    """Write ``clip`` as ``<stem>.<fmt>`` inside ``directory``."""
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    return write_clip(clip, directory / f"{stem}.{fmt.lower().lstrip('.')}", bitrate)


# --------------------------------------------------------------------------
# Text
# --------------------------------------------------------------------------


def lesson_to_text(lesson: Lesson) -> str:
    level = get_level(lesson.level)
    lines: List[str] = []
    title = lesson.title_ja or lesson.topic_label
    lines.append(f"{title}".strip())
    if lesson.title_zh:
        lines.append(lesson.title_zh)
    lines.append("=" * 46)
    lines.append(f"级别 Level : {level.code}（{level.label_zh} / {level.label_en}）")
    lines.append(f"主题 Topic : {lesson.topic_label or lesson.topic}")
    lines.append(f"来源 Source: {lesson.source_label or lesson.source}")
    if lesson.source_url:
        lines.append(f"           {lesson.source_url}")
    lines.append(f"生成时间   : {lesson.created_at}")
    lines.append(f"预计时长   : 约 {lesson.estimated_seconds} 秒")
    lines.append("")

    lines.append("【日本語（ふりがな付き）】")
    for index, sentence in enumerate(lesson.sentences, 1):
        lines.append(f"{index:2d}. {sentence.furigana_inline}")
    lines.append("")

    lines.append("【かな だけ / 仅假名】")
    for index, sentence in enumerate(lesson.sentences, 1):
        lines.append(f"{index:2d}. {sentence.kana or sentence.ja}")
    lines.append("")

    if any(s.zh for s in lesson.sentences):
        lines.append("【中文翻译】")
        for index, sentence in enumerate(lesson.sentences, 1):
            lines.append(f"{index:2d}. {sentence.zh}")
        lines.append("")

    if lesson.vocab:
        lines.append("【単語 / 生词】")
        for entry in lesson.vocab:
            kana = f"（{entry.kana}）" if entry.kana and entry.kana != entry.word else ""
            lines.append(f"  {entry.word}{kana}  {entry.zh}")
        lines.append("")

    if lesson.warnings:
        lines.append("【提示】")
        for warning in lesson.warnings:
            lines.append(f"  * {warning}")
        lines.append("")

    lines.append(f"-- generated by {APP_NAME} {__version__}")
    return "\n".join(lines)


def export_text(lesson: Lesson, directory: Path, stem: str) -> Path:
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{stem}.txt"
    path.write_text(lesson_to_text(lesson), encoding="utf-8")
    return path


# --------------------------------------------------------------------------
# HTML (real <ruby> furigana - the nicest way to study or print)
# --------------------------------------------------------------------------

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{
    font-family: "Yu Gothic", "Hiragino Kaku Gothic ProN", "Noto Sans JP",
                 "Microsoft YaHei", sans-serif;
    margin: 0; padding: 2rem 1rem; line-height: 2.1;
    background: #fbfaf7; color: #21201c;
  }}
  main {{ max-width: 46rem; margin: 0 auto; }}
  h1 {{ font-size: 1.6rem; margin: 0 0 .2rem; }}
  .subtitle {{ color: #6b6862; margin: 0 0 1.4rem; font-size: 1rem; }}
  .meta {{ font-size: .85rem; color: #6b6862; border-bottom: 1px solid #e2ded4;
           padding-bottom: 1rem; margin-bottom: 1.6rem; }}
  .meta span {{ margin-right: 1.2rem; white-space: nowrap; }}
  ol {{ padding-left: 1.6rem; }}
  li {{ margin-bottom: 1.3rem; }}
  .ja {{ font-size: 1.28rem; }}
  ruby rt {{ font-size: .52em; color: #8a6d3b; font-weight: 400; }}
  .zh {{ color: #55636b; font-size: .95rem; line-height: 1.7; margin-top: .15rem; }}
  .vocab {{ margin-top: 2.4rem; border-top: 1px solid #e2ded4; padding-top: 1.2rem; }}
  .vocab table {{ border-collapse: collapse; width: 100%; font-size: .95rem; }}
  .vocab td {{ padding: .35rem .6rem; border-bottom: 1px solid #eee9df; }}
  .vocab td:first-child {{ font-weight: 600; white-space: nowrap; }}
  .notes {{ margin-top: 2rem; font-size: .88rem; color: #8a6d3b; }}
  footer {{ margin-top: 2.5rem; font-size: .8rem; color: #96928a; }}
  @media (prefers-color-scheme: dark) {{
    body {{ background: #16161a; color: #e8e6e1; }}
    .subtitle, .meta, footer {{ color: #9a968e; }}
    .meta, .vocab {{ border-color: #2e2e34; }}
    .vocab td {{ border-color: #26262b; }}
    .zh {{ color: #a8b3ba; }}
    ruby rt {{ color: #c9a86a; }}
  }}
  @media print {{ body {{ background: #fff; }} }}
</style>
</head>
<body>
<main>
<h1>{title}</h1>
<p class="subtitle">{subtitle}</p>
<div class="meta">{meta}</div>
<ol>
{items}
</ol>
{vocab}
{notes}
<footer>Generated by {app} {version} - {created}</footer>
</main>
</body>
</html>
"""


def lesson_to_html(lesson: Lesson) -> str:
    level = get_level(lesson.level)
    items: List[str] = []
    for sentence in lesson.sentences:
        block = [f'  <li><div class="ja">{sentence.html_ruby}</div>']
        if sentence.zh:
            block.append(f'      <div class="zh">{escape(sentence.zh)}</div>')
        block.append("  </li>")
        items.append("\n".join(block))

    meta_parts = [
        f"<span>级别 {escape(level.code)}（{escape(level.label_zh)}）</span>",
        f"<span>主题 {escape(lesson.topic_label or lesson.topic)}</span>",
        f"<span>约 {lesson.estimated_seconds} 秒</span>",
    ]
    if lesson.source_label:
        if lesson.source_url:
            meta_parts.append(
                f'<span>来源 <a href="{escape(lesson.source_url)}">'
                f"{escape(lesson.source_label)}</a></span>"
            )
        else:
            meta_parts.append(f"<span>来源 {escape(lesson.source_label)}</span>")

    vocab_html = ""
    if lesson.vocab:
        rows = "\n".join(
            f"    <tr><td>{escape(v.word)}</td><td>{escape(v.kana)}</td>"
            f"<td>{escape(v.zh)}</td></tr>"
            for v in lesson.vocab
        )
        vocab_html = (
            '<section class="vocab"><h2 style="font-size:1.05rem">単語 / 生词</h2>\n'
            f"  <table>\n{rows}\n  </table>\n</section>"
        )

    notes_html = ""
    if lesson.warnings:
        notes = "".join(f"<li>{escape(w)}</li>" for w in lesson.warnings)
        notes_html = f'<div class="notes"><ul>{notes}</ul></div>'

    return _HTML_TEMPLATE.format(
        title=escape(lesson.title_ja or lesson.topic_label or "AutoTutor"),
        subtitle=escape(lesson.title_zh or ""),
        meta="".join(meta_parts),
        items="\n".join(items),
        vocab=vocab_html,
        notes=notes_html,
        app=APP_NAME,
        version=__version__,
        created=escape(lesson.created_at),
    )


def export_html(lesson: Lesson, directory: Path, stem: str) -> Path:
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{stem}.html"
    path.write_text(lesson_to_html(lesson), encoding="utf-8")
    return path


# --------------------------------------------------------------------------
# Subtitles
# --------------------------------------------------------------------------


def _srt_timestamp(seconds: float) -> str:
    if seconds < 0:
        seconds = 0.0
    millis = int(round(seconds * 1000))
    hours, millis = divmod(millis, 3_600_000)
    minutes, millis = divmod(millis, 60_000)
    secs, millis = divmod(millis, 1000)
    return f"{hours:02d}:{minutes:02d}:{secs:02d},{millis:03d}"


def lesson_to_srt(lesson: Lesson, timings: Sequence) -> str:
    blocks: List[str] = []
    for order, timing in enumerate(timings, 1):
        if timing.index >= len(lesson.sentences):
            continue
        sentence = lesson.sentences[timing.index]
        text = sentence.ja
        if sentence.zh:
            text += "\n" + sentence.zh
        blocks.append(
            f"{order}\n"
            f"{_srt_timestamp(timing.start)} --> {_srt_timestamp(timing.end)}\n"
            f"{text}\n"
        )
    return "\n".join(blocks)


def export_srt(lesson: Lesson, timings: Sequence, directory: Path, stem: str) -> Path:
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{stem}.srt"
    path.write_text(lesson_to_srt(lesson, timings), encoding="utf-8")
    return path


# --------------------------------------------------------------------------
# JSON (re-openable inside the app)
# --------------------------------------------------------------------------


def export_json(lesson: Lesson, directory: Path, stem: str) -> Path:
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{stem}.json"
    path.write_text(
        json.dumps(lesson.to_dict(), ensure_ascii=False, indent=2), encoding="utf-8"
    )
    return path


# --------------------------------------------------------------------------
# Bundle
# --------------------------------------------------------------------------


def export_bundle(
    lesson: Lesson,
    directory: Path,
    *,
    clip=None,
    timings: Optional[Sequence] = None,
    stem: str = "",
    audio_format: str = "mp3",
    bitrate: int = 128,
    include_text: bool = True,
    include_html: bool = True,
    include_srt: bool = True,
    include_json: bool = False,
) -> ExportResult:
    """Export everything the learner asked for in one go."""
    result = ExportResult()
    directory = Path(directory)
    stem = stem or lesson.slug()

    if clip is not None:
        try:
            result.files.append(export_audio(clip, directory, stem, bitrate, audio_format))
        except UnsupportedFormat as exc:
            result.warnings.append(str(exc))
            try:
                result.files.append(export_audio(clip, directory, stem, bitrate, "mp3"))
            except Exception as inner:  # pragma: no cover - defensive
                result.warnings.append(f"音频导出失败：{inner}")
        except Exception as exc:  # pragma: no cover - defensive
            result.warnings.append(f"音频导出失败：{exc}")

    if include_text:
        result.files.append(export_text(lesson, directory, stem))
    if include_html:
        result.files.append(export_html(lesson, directory, stem))
    if include_json:
        result.files.append(export_json(lesson, directory, stem))
    if include_srt:
        if timings:
            result.files.append(export_srt(lesson, timings, directory, stem))
        else:
            result.warnings.append("当前音频无法计算逐句时间轴，已跳过字幕文件。")

    return result
